import { Link } from 'react-router-dom';

type Product = 'property' | 'food';

const copy: Record<Product, { name: string; description: string; sections: Array<[string, string, string]> }> = {
  property: { name: 'WhatsChat Property', description: 'Property operations powered by the conversations already happening on WhatsApp.', sections: [['Conversations', 'Review tenant and team conversations in one operational inbox.', '/chats'], ['Maintenance', 'Triage issues, safety signals and maintenance requests.', '/property/operations'], ['Work Orders', 'Track assigned and pending operational work.', '/property/operations'], ['Properties', 'Manage property-level operational context.', '/property/operations'], ['Vendors', 'Coordinate contractors and vendors around work.', '/property/operations'], ['Reports', 'Review operational performance and activity.', '/dashboard'], ['Settings', 'Manage product and connection settings.', '/settings']] },
  food: { name: 'WhatsChat Food', description: 'A focused food ordering and operations workspace built around WhatsApp.', sections: [['Conversations', 'Handle customer messages without leaving the operations workspace.', '/chats'], ['Orders', 'Review incoming, active and completed food orders.', '/food/operations'], ['Menu', 'Manage menu items, availability and prices.', '/food/operations'], ['Kitchen', 'Coordinate preparation and operational status.', '/food/operations'], ['Pickup & Delivery', 'Track fulfilment, pickup and delivery details.', '/food/operations'], ['Customers', 'Review customer context and repeat orders.', '/crm'], ['Reports', 'Monitor demand and operational performance.', '/dashboard'], ['Settings', 'Manage product and connection settings.', '/settings']] },
};

export function ProductDashboardPage({ product }: { product: Product }) { const config = copy[product]; return <div className="min-h-0 flex-1 overflow-auto bg-surface-0 p-5 sm:p-8"><div className="mx-auto max-w-6xl"><div className="rounded-2xl border border-border-subtle bg-surface-1 p-6 sm:p-8"><p className="text-meta font-semibold tracking-widest text-accent">PRODUCT WORKSPACE</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{config.name}</h1><p className="mt-3 max-w-2xl text-body leading-7 text-fg-secondary">{config.description}</p><div className="mt-6 flex flex-wrap gap-3 text-caption"><span className="rounded-full bg-success/15 px-3 py-1.5 text-success">WhatsApp connection managed separately</span><span className="rounded-full bg-surface-2 px-3 py-1.5 text-fg-secondary">Focused product navigation</span></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{config.sections.map(([title, description, to]) => <Link key={title} to={to} className="rounded-xl border border-border-subtle bg-surface-1 p-5 transition hover:border-accent/50 hover:bg-surface-2"><h2 className="text-title font-semibold">{title}</h2><p className="mt-2 text-caption leading-6 text-fg-secondary">{description}</p><span className="mt-4 inline-block text-caption font-semibold text-accent">Open {title} →</span></Link>)}</div></div></div>; }
