-- Reserved migration number retained for migration-history compatibility.
-- Platform action, approval and audit tables are defined in 901_platform_runtime.sql.
-- Subsequent hardening is handled by 904 and later migrations.
